### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by goldjee** [ags131/steamMinigameSlaveScript#2] opened 2015-06-14 18:22 UTC
At start spawns 4 slaves (setting set to 5). No buttons 'Spawn/kill' are shown.

**Comment by ags131** [comment] 2015-06-14 18:25
Its spawning 5 windows here, and the buttons have been moved down next to the sound toggles. 
You using firefox or chrome?

**Comment by goldjee** [comment] 2015-06-14 19:01
Latest Chrome

**Comment by ags131** [comment] 2015-06-15 04:23
I'm closing this as I'm unable to reproduce, you may want to try forcing an update to newest version.

**Closed by ags131** 2015-06-15 04:23 UTC
Labels: bug
